### ISSUE TITLE
Can't seem to get it to work

### ISSUE THREAD

**Issue by BlyatFirmeza** [peewpw/Invoke-PSImage#1]
I embeded "shutdown -s -t 0" into a .jpeg and output into .png
But when i open the .png nothing executes

**Comment by DeeLMind** [comment]
So do I

**Comment by tosh1437** [comment]
I am unable to get it to even produce the output png file.

**Comment by crickett** [comment]
The issue I had was "Index was outside the bounds of the array"

I solved this by using a larger input file.

**Comment by Fintotini** [comment]
hi, 
the PSimage script seems working fine with a lager image but the ps script executed when i launch the image doesn't starts.

it seems that miss the invoke command into the PSimage scritp. 

using this command:
Invoke-PSImage -Script .\Get-ComputerDetails.ps1 -Image .\city.png -Out .\test3.png

output:
sal a New-Object;Add-Type -AssemblyName "System.Drawing";$g= a System.Drawing.Bitmap("C:\Users\Marco\Downloads\Invoke-PSImage-master\test3.png");$o= a Byte[] 19200;(0..9)|% {foreach($x in (0..1919)){$p=$g.GetPixel($x,$_);$o[$_*1920+$x]=(
[math]::Floor(($p.B -band 15)*16) -bor ($p.G -band 15))}};$g.Dispose();IEX([System.Text.Encoding]::ASCII.GetString($o[0..17706]))

**Comment by Castaldio86** [comment]
+1

tried it in files between 500KB and 25MB

And a .ps1 containing

& "C:\Windows\System32\calc.exe"

**Comment by maysam-h** [comment]
everytime I run the outliner, I get this issue. I double check this command, but all the brackets has a closing. any help please, thanks in advance.

![image](https://user-images.githubusercontent.com/17390164/34133047-07ab9492-e453-11e7-99ad-b4c448608bdf.png)

**Comment by tasox** [comment]
I have the same problem with @maysam-h

**Comment by maysam-h** [comment]
@tasox thanks for the tip. 
But it does not work for me. I even updated to make sure I have the updates after the last commit.
Here is a screenshot of the commands I invoke. is there anything I am missing please?
Thanks in advance.

![image](https://user-images.githubusercontent.com/17390164/34207502-02aff4f4-e58b-11e7-9a9c-7c5cce732cf3.png)

**Comment by tasox** [comment]
@maysam-h in your batchfile.ps1 you have some functions right? Try in the end of every function to put "**;**"  

For Example:

function test { <your code>}**;**

But now you have a different error from previous. Please check very carefully your "batchfile.ps1" and find somewhere in your code "&" character because this character produce this error.

**Comment by maysam-h** [comment]
@tasox It seems to be strange because my batch file does not have a function or '&'. Here is a contents of my batch file. 

`echo off
::creating some test fodlers

mkdir ali-here
mkdir ali-here2
mkdir ali-here3
exit`

I assume its the oneliner because the error says "At Line:1 char:309" which is exactly the bracket after "IEX".

**Comment by peewpw** [comment]
These all look like errors in the source scripts. Please open a new issue if you cannot generate a one-liner for a working script.

closing.
